[package]
name = "bot"
version = "0.1.0"
authors = ["Vadim <ukintchanel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gstd = { path = "../../../gstd", features = ["debug"] }
codec = { package = "parity-scale-codec", version = "1.3", features = ["derive"] }
demo-chat = { path = ".." }