[package]
name = "gear-node-rti"
version = "2.0.0"
authors = ["Anonymous"]
description = "Runtime iterface of the Gear node"
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-runtime-interface = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-externalities = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
gear-core = { path = "../../gear-core", optional = true }
gear-common = { path = "../common" }
log = "0.4"

[features]
default = ["std"]
std = [
    "gear-core",
    "sp-core/std",
    "codec/std",
    "gear-common/std",
    "sp-externalities/std",
    "sp-runtime-interface/std",
]
