[package]
name = "gear-program"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "bin/gear.rs"
name = "gear"

[dependencies]
dirs = "4.0.0"
env_logger = "0.9.0"
git2 = "^0.14"
log = "0.4.16"
structopt = "0.3.26"
subxt = "0.20.0"

