[package]
name = "test-gear"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gear-core = { path = "../gear-core" }
anyhow = "1"
serde = "*"
serde_json = "*"
hex = "0.4.2"
termion = "1.5.6"
env_logger = "0.8"


[workspace]
members = ["runner"]

# [[bin]]
# name = "testgear"
# path = "src/main.rs"

[[bin]]
name = "gtest"
path = "runner/src/main.rs"