[package]
name = "gear-core"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "2", features = ["derive"] }
wasmtime = { version = "0.22", default-features = false, features = ["parallel-compilation"] }
derive_more = "0.99"
anyhow = "1"
log = "0.4"
libc = "0.2"

[dev-dependencies]
wabt = "0.10.0"

[features]
default = []
strict = []
