[package]
name = "gear-program"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "bin/gear.rs"
name = "gear"

[dependencies]
async-std = "1.11.0"
dirs = "4.0.0"
env_logger = "0.9.0"
log = "0.4.16"
structopt = "0.3.26"
subxt = "0.20.0"
thiserror = "1.0.31"
