[package]
name = "gear-test-cli"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
codec = { version = "2.0.0", package = "parity-scale-codec" }
structopt = "0.3.8"
serde_json = "1.0.64"
anyhow = "1.0.40"
termion = "1.5.6"
regex = "1.4"

# Substrate deps
sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-service = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sp-io = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-system = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }

# Internal deps
gear-core = { path = "../../../gear-core" }
test-gear-sample = { path = "../../../test-gear/sample" }
rti = { package = "gear-node-rti", path = "../../rti" }
gear-runtime = { path = "../../runtime" }
