[package]
authors = ['Anonymous']
edition = '2018'
name = 'pallet-gear'
version = "2.0.0"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
common = { package = "gear-common", path = "../../common", default-features = false }
rti = { package = "gear-node-rti", path = "../../rti", default-features = false }

[dev-dependencies]
serde = "1.0.101"
env_logger = "0.8"
wabt = "0.10"

[dependencies.frame-support]
default-features = false
version = "3.0.0"
git = "https://github.com/paritytech/substrate.git"

[dependencies.frame-system]
default-features = false
version = "3.0.0"
git = "https://github.com/paritytech/substrate.git"

[dependencies.sp-core]
default-features = false
version = "3.0.0"
git = "https://github.com/paritytech/substrate.git"

[dependencies.sp-std]
default-features = false
version = "3.0.0"
git = "https://github.com/paritytech/substrate.git"

[dependencies.sp-io]
default-features = false
version = "3.0.0"
git = "https://github.com/paritytech/substrate.git"

[dev-dependencies.sp-runtime]
default-features = false
version = "3.0.0"
git = "https://github.com/paritytech/substrate.git"

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'rti/std',
	'sp-io/std',
	'sp-std/std',
	'sp-core/std',
	'common/std',
]
