[package]
name = "gear-test-runner"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gear-core = { path = "../../gear-core" }
anyhow = "1"
serde = "*"
serde_json = "*"

[[bin]]
name = "gtest"
path = "src/main.rs"
