name: Rust

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master, ci-test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: "Checkout test-gear"
      with:
        repository: 'gear-computing/test-gear'
        path: "test-gear"
    - uses: actions/checkout@v2
      name: "Checkout gear-core"
      with:
        repository: 'gear-computing/gear-core'
        token: ${{ secrets.GEAR_CORE_PAT }}
        path: gear-core
    - uses: actions/checkout@v2
      name: "Checkout gstd"
      with:
        repository: 'gear-computing/gstd'
        token: ${{ secrets.GEAR_CORE_PAT }}
        path: gstd
    - name: Install latest nightly & WASM toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: wasm32-unknown-unknown
    - name: Build WASM
      run: >
        cd test-gear &&
        cargo +nightly build --manifest-path=demo-ping/Cargo.toml --target=wasm32-unknown-unknown --release &&
        cargo +nightly build --manifest-path=demo-fib/Cargo.toml --target=wasm32-unknown-unknown --release &&
        cargo +nightly build --manifest-path=demo-sum/Cargo.toml --target=wasm32-unknown-unknown --release &&
        cargo +nightly build --manifest-path=demo-vec/Cargo.toml --target=wasm32-unknown-unknown --release
    - name: Run tests
      run: cd test-gear/runner && cargo test
    - name: Run testsuite
      run: cd test-gear/runner && cargo run --release ./sample/*.json
