name: Rust

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master, ci-test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'gear-computing/test-gear'
        path: "test-gear"
    - uses: actions/checkout@v2
      with:
        repository: 'gear-computing/gear-core'
        token: ${{ secrets.GEAR_CORE_PAT }} # `GitHub_PAT` is a secret that contains your PAT
        path: gear-core
    - name: Build
      run: cd test-gear && cargo build --verbose
    - name: Run tests
      run: cd test-gear && cargo test --verbose
