name: Rust

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master, ci-test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout gear-core
      run: git clone https://github.com/gear-computing/gear-core ../gear-core
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
