name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features=strict
    - name: Run tests
      run: cargo test --features=strict
    - name: Run gear-backend tests
      run: cd gear-backend && cargo test --all-features
    - name: Run gear-runner tests
      run: cd gear-runner && cargo test