name: Rust

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master, ci-test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: "Checkout gear-node"
      with:
        path: "gear-node"
    - uses: actions/checkout@v2
      name: "Checkout gear-core"
      with:
        repository: 'gear-computing/gear-core'
        token: ${{ secrets.GEAR_PAT }}
        path: gear-core
    - uses: actions/checkout@v2
      name: "Checkout test-gear"
      with:
        repository: 'gear-computing/test-gear'
        token: ${{ secrets.GEAR_PAT }}
        path: test-gear
    - name: Install latest nightly & WASM toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: wasm32-unknown-unknown
    - name: Build
      run: cd gear-node && cargo build --release
    - name: Run tests
      run: cd gear-node && cargo test --release --all
